name: Build and deploy Node.js app to Azure Web App - api-willard

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Solo clona la última confirmación

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Verify artifact contents
        run: ls -R  # Imprime la estructura de directorios para asegurarte de que el build esté en la ruta esperada

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            ./dist  # Cambia 'dist' por la carpeta donde está el build si es diferente
            !node_modules/**  # Excluye node_modules para evitar demasiados archivos
            !.git/**  # Excluye la carpeta .git
            !coverage/**  # Excluye la carpeta de coverage si existe

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'api-willard'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AD1AFF332A4B48E2810D80C8F1150DDB }}
